apiVersion: v1
kind: Service
metadata:
  labels:
    app: rasmus-nodejs-docker-webapp
  name: rasmus-nodejs-docker-webapp
  namespace: workshop

spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: rasmus-nodejs-docker-webapp
